### ISSUE TITLE
Uploading a Base64. Error 'Payload Too Large' 

### ISSUE THREAD

**Issue by carlosen14** [eukaprotech/networking#2]
Trying to upload an image as Base64 (268792 chars length, is not a huge one) gives me `Payload Too Large` error.

I was working with another lib but decided to use yours, previous lib worked fine the upload, but was missing status codes and errors when failing. 

Server in NodeJS w/ Express is prepared to receive huge files (up to 50 Mb).

Now, the POST request don't even reach the server side.

Any solution?

**Comment by eukaprotech** [comment]
Apologies for the late reply. 

Payload Too Large is a HTTP error 413. The 413 Payload Too Large response status code indicates that the request entity is larger than limits defined by server.

Since you have already stated that the server is configured to receive huge files up to 50MB, I would like to know the actual status code of the error you are receiving.

Irregardless, I will look into the issue closely and get possible causes of the error.

**Comment by carlosen14** [comment]
sorry, i migrated to another library.. whit the same server config, it was working without modifications. I appreciate your effort.

**Comment by eukaprotech** [comment]
Well received and noted.
